### ISSUE TITLE
Workshop image is broken - python dependency changed

### ISSUE THREAD

**Issue by shookim** [OWASP/crAPI#14]
Traceback (most recent call last):

  File "manage.py", line 36, in <module>

    main()

  File "manage.py", line 32, in main

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute

    django.setup()

  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate

    app_config = AppConfig.create(entry)

  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 116, in create

    mod = import_module(mod_path)

  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 843, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/app/crapi/apps.py", line 22, in <module>

    import bcrypt

  File "/usr/local/lib/python3.8/site-packages/bcrypt/__init__.py", line 25, in <module>

    from . import _bcrypt

ImportError: Error loading shared library libffi.so.7: No such file or directory (needed by /usr/local/lib/python3.8/site-packages/_cffi_backend.cpython-38-x86_64-linux-gnu.so)

**Comment by idan-aharoni** [comment]
Seems like Alpine broke Crapi? 
When looking at the docker it seems like it installs a different version of libffi than the one that crapi needs

**Comment by piyushroshan** [comment]
Thank you for the context. That gives me enough information to take it further

**Comment by idan-aharoni** [comment]
@piyushroshan the problem is probably because there is inconsistency between the alpine versions of the workshop, for build 3.13 is being used and for the actual application 3.15 is being used, changing both to the same version should work

**Comment by piyushroshan** [comment]
Thank you for your help. That was exactly the issue. The runtime version of alpine was fixed to latest but build to 3.13. Moved both to 3.15
